name: Hourly Velib Availability Download - Python Script

on:
  schedule:
    - cron: "0 * * * *"  # Run every hour

jobs:
  download-velib-data:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Download Velib Availability Data
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: |
          python src/velib_prediction/pipelines/download_data/download_data_run.py

      - name: Commit and push
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Data updated" -a
          git push