name: Hourly Velib Availability Download

on:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: "0 * * * *"  # Run every hour

jobs:
  download-velib-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: pipx install poetry

      - name: Setup Python & Install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.8'
          cache: 'poetry'
      - run: poetry install

      - name: Download Velib Availability Data
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run:
          poetry run python velib_prediction/src/velib_prediction/pipelines/download_data/download_data_run.py
    
      - name: Commit and push
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Data updated" -a
          git push
