# Create workflow to deploy kedro viz on branches
name: Publish and share Kedro Viz

permissions:

    # The contents write permission is required to use the action 
    # if your GitHub publishing source is a branch
    contents: write 

    # The pages and id-token write permissions are required to use 
    # the action if your GitHub publishing source is a custom 
    # GitHub Actions workflow
    pages: write 
    id-token: write

# Triggers
on:
    pull_request:
        branches:
        - main
        - dev
    push:
        branches:
        - main
        - dev
    workflow_dispatch:

# Job
jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.11"]

        steps:
            - name: Fetch the repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            # Install dependencies
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install .[dev]

            # Use the action
            - name: Deploy Kedro-Viz to Github Pages
              uses: kedro-org/publish-kedro-viz@v2
