# Create workflow to deploy kedro viz on branches
name: Kedro-Viz

# Triggers
on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

# Job
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    permissions:
      contents: write

    steps:
      - name: Fetch the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install uv
          uv venv .venv
          uv sync --extra dev

      # Use the action
      - name: Deploy Kedro-Viz to Github Pages
        uses: kedro-org/publish-kedro-viz@v2
